### ISSUE TITLE
Problem with Select the file window in Trajectory inference tab

### ISSUE THREAD

**Issue by alevigi** [KirstLab/asc_seurat#13]
Hello.

I've been having some issues with loading the object for a trajectory analysis. When I click on it only a white line comes up instead of the list of files in my RDS folder. 

I tried using different browser but it does not seem to change. 

Thanks in advance for your help.

Alessandra

**Comment by fmalmeida** [comment]
Hi Alessandra,
Thank you for using Asc-Seurat.

One of the possible problems is the browser cache. Did you tried to refresh the program's page one or two times?

If this does not help, it may be a problem with the organization or nomination of the directories (we needed to establish a specific structure and name for input dirs).

Is your RDS folder named "RDS_files"?
Is it placed inside the directory where you're calling Asc-Seurat?
Could you send us a tree visualization of the directory where you're calling the program?

Felipe.

**Comment by alevigi** [comment]
Hi, yes I tried all of the above. 

I used the tool already few times for an analysis and it always worked. I'm trying to repeat the analysis the last time with another dataset and it's giving me this problem.

My folders are:
data
images
RDS_files (and my file it's there)
www

I don't think it has to do with the folder organisation otherwise I would have had the same problem before. 

I thought something happened on your side, perhaps you working on the code that's why I asked. 

Thank you for your help.

Alessandra

**Comment by fmalmeida** [comment]
Yes, everything looks good on your folders.

That's interesting ... because we did not changed nothing in the code recently, and since it actually uses the code stored in the Docker images instead of the one in github I am sure that you're using the same code when it worked.

I assume you have tried everything right? (Removing and downloading the docker image. Killing and reopening the container. etc.). As I see it really looks like its something with the caches, probably the docker caches. You're running it in which operating system?

That's really weird. @wendelljpereira you have any thoughts?

**Comment by alevigi** [comment]
Problem found: because I was killing and reopening the container, new folders (RDS_files, www, data) were appearing in my home directory (not in my_project folder). So the tool was pointing to the new RDS_files folder that was empty. 

I'm using MacOS

**Comment by fmalmeida** [comment]
Just to know, now that you're opening the container from your project folder it is correctly pointing to the populated folder, right?

Glad to hear that it is solved.

Thanks for using the software and reporting the issues.

Felipe.
